[project]
name = "github-practical"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vaibhavclover", email = "vaibhav.nhayade@cloverinfotech.com" }
]
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
github-practical = "github_practical:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
